return {
    currency = '¥',
    mods = {
        {id = 0,  label = 'スポイラー',              category = 'parts'},
        {id = 1,  label = 'フロントバンパー',         category = 'parts'},
        {id = 2,  label = 'リアバンパー',          category = 'parts'},
        {id = 3,  label = 'サイドスカート',           category = 'parts'},
        {id = 4,  label = 'マフラー',              category = 'parts'},
        {id = 5,  label = 'ロールケージ',            category = 'parts'},
        {id = 6,  label = 'グリル',               category = 'parts'},
        {id = 7,  label = 'ボンネット',                 category = 'parts'},
        {id = 8,  label = '左フェンダー',          category = 'parts'},
        {id = 9,  label = '右フェンダー',         category = 'parts'},
        {id = 10, label = 'ルーフ',                 category = 'parts'},
        {id = 11, label = 'エンジンアップグレード',       category = 'performance'},
        {id = 12, label = 'ブレーキアップグレード',        category = 'performance'},
        {id = 13, label = 'トランスミッションアップグレード', category = 'performance'},
        {id = 14, label = 'ホーン',                category = 'parts'},
        {id = 15, label = 'サスペンションアップグレード',   category = 'performance'},
        {id = 16, label = 'アーマーアップグレード',        category = 'performance', enabled = false},
        {id = 17, label = 'ニトロ',              category = 'performance', enabled = false},
        {id = 18, label = 'ターボアップグレード',        category = 'performance'},
        {id = 19, label = 'サブウーファー',            category = 'parts'},
        -- {id = 20, label = 'タイヤスモーク',                category = 'colors'},
        {id = 21, label = 'ハイドロ',           category = 'parts'},
        -- {id = 22, label = 'ゼノンライト',         category = 'colors'},
        -- {id = 23, label = 'ホイール', category = 'parts'},
        -- {id = 24, label = 'リアホイール/ハイドロ', category = 'parts'},
        {id = 25, label = 'プレートホルダー',         category = 'parts'},
        {id = 26, label = 'バニティプレート',        category = 'parts'},
        {id = 27, label = 'トリム A',               category = 'parts'},
        {id = 28, label = 'オーナメント',            category = 'parts'},
        {id = 29, label = 'ダッシュボード',            category = 'parts'},
        {id = 30, label = 'ダイヤル',                 category = 'parts'},
        {id = 31, label = 'ドアスピーカー',         category = 'parts'},
        {id = 32, label = 'シート',                category = 'parts'},
        {id = 33, label = 'ステアリングホイール',       category = 'parts'},
        {id = 34, label = 'シフターレバー',       category = 'parts'},
        {id = 35, label = 'プラーク',               category = 'parts'},
        {id = 36, label = 'スピーカー',              category = 'parts'},
        {id = 37, label = 'トランク',                category = 'parts'},
        {id = 38, label = 'ハイドロ',            category = 'parts'},
        {id = 39, label = 'エンジンブロック',         category = 'parts'},
        {id = 40, label = 'エアフィルター',           category = 'parts'},
        {id = 41, label = 'ストラット',                category = 'parts'},
        {id = 42, label = 'アーチカバー',           category = 'parts'},
        {id = 43, label = 'アンテナ',               category = 'parts'},
        {id = 44, label = 'トリム B',               category = 'parts'},
        {id = 45, label = '燃料タンク',            category = 'parts'},
        {id = 46, label = '左ドア',            category = 'parts'},
        {id = 47, label = '右ドア',           category = 'parts'},
        -- {id = 48, label = 'リベリー',               category = 'colors'},
        {id = 49, label = 'ライトバー',             category = 'parts'},
    },

    -- https://docs.fivem.net/natives/?_0x4F1D4BE3A7F24601
    paints = {
        Classic = {
            {id = 0,   label = 'ブラック'},
            {id = 1,   label = 'グラファイト'},
            {id = 2,   label = 'ブラックスチール'},
            {id = 3,   label = 'ダークスチール'},
            {id = 4,   label = 'シルバー'},
            {id = 5,   label = 'ブルウィッシュシルバー'},
            {id = 6,   label = 'ロールスチール'},
            {id = 7,   label = 'シャドウシルバー'},
            {id = 8,   label = 'ストーンシルバー'},
            {id = 9,   label = 'ミッドナイトシルバー'},
            {id = 10,  label = '鋳鉄シルバー'},
            {id = 11,  label = 'アンラサイトブラック'},
            {id = 27,  label = 'レッド'},
            {id = 28,  label = 'トリノレッド'},
            {id = 29,  label = 'フォーミュラレッド'},
            {id = 30,  label = 'ブレイズレッド'},
            {id = 31,  label = 'グレースレッド'},
            {id = 32,  label = 'ガーネットレッド'},
            {id = 33,  label = 'サンセットレッド'},
            {id = 34,  label = 'カベルネレッド'},
            {id = 35,  label = 'キャンディレッド'},
            {id = 36,  label = 'サンライズオレンジ'},
            {id = 38,  label = 'オレンジ'},
            {id = 49,  label = 'ダークグリーン'},
            {id = 50,  label = 'レーシンググリーン'},
            {id = 51,  label = 'シーグリーン'},
            {id = 52,  label = 'オリーブグリーン'},
            {id = 53,  label = 'ブライトグリーン'},
            {id = 54,  label = 'ガソリングリーン'},
            {id = 61,  label = 'ギャラクシーブルー'},
            {id = 62,  label = 'ダークブルー'},
            {id = 63,  label = 'サクソンブルー'},
            {id = 64,  label = 'ブルー'},
            {id = 65,  label = 'マリナーブルー'},
            {id = 66,  label = 'ハーバーブルー'},
            {id = 67,  label = 'ダイアモンドブルー'},
            {id = 68,  label = 'サーフブルー'},
            {id = 69,  label = 'ノーティカルブルー'},
            {id = 70,  label = 'ウルトラブルー'},
            {id = 71,  label = 'シャフターパープル'},
            {id = 72,  label = 'スピネーカーパープル'},
            {id = 73,  label = 'レーシングブルー'},
            {id = 74,  label = 'ライトブルー'},
            {id = 88,  label = 'イエロー'},
            {id = 89,  label = 'レースイエロー'},
            {id = 90,  label = 'ブロンズ'},
            {id = 91,  label = 'デューイエロー'},
            {id = 92,  label = 'ライムグリーン'},
            {id = 94,  label = 'フェルツァーブラウン'},
            {id = 95,  label = 'クリーンブラウン'},
            {id = 96,  label = 'チョコレートブラウン'},
            {id = 97,  label = 'メープルブラウン'},
            {id = 98,  label = 'サドルブラウン'},
            {id = 99,  label = 'ブリーチブラウン'},
            {id = 100, label = 'モスブラウン'},
            {id = 101, label = 'バイソンブラウン'},
            {id = 102, label = 'ウッドビーチブラウン'},
            {id = 103, label = 'ビーチウッドブラウン'},
            {id = 104, label = 'シエナブラウン'},
            {id = 105, label = 'サンディブラウン'},
            {id = 106, label = 'ブリーチブラウン'},
            {id = 107, label = 'クリーム'},
            {id = 111, label = 'アイスホワイト'},
            {id = 112, label = 'フロストホワイト'},
            {id = 135, label = 'ホットピンク'},
            {id = 136, label = 'サーモンピンク'},
            {id = 137, label = 'フィスターピンク'},
            {id = 138, label = 'ブライトオレンジ'},
            {id = 141, label = 'ミッドナイトブルー'},
            {id = 142, label = 'ミッドナイトパープル'},
            {id = 143, label = 'ワインレッド'},
            {id = 145, label = 'ブライトパープル'},
            {id = 147, label = 'カーボンブラック'},
            {id = 150, label = 'ラヴァレッド'},
        },
        Matte = {
            {id = 12,  label = 'ブラック'},
            {id = 13,  label = 'グレー'},
            {id = 14,  label = 'ライトグレー'},
            {id = 39,  label = 'レッド'},
            {id = 40,  label = 'ダークレッド'},
            {id = 41,  label = 'オレンジ'},
            {id = 42,  label = 'イエロー'},
            {id = 55,  label = 'ライムグリーン'},
            {id = 82,  label = 'ダークブルー'},
            {id = 83,  label = 'ブルー'},
            {id = 84,  label = 'ミッドナイトブルー'},
            {id = 131, label = 'アイスホワイト'},
            {id = 148, label = 'シャフターパープル'},
            {id = 149, label = 'ミッドナイトパープル'},
            {id = 151, label = 'フォレストグリーン'},
            {id = 152, label = 'オリーブドラブ'},
            {id = 153, label = 'ダークアース'},
            {id = 154, label = 'デザートタン'},
            {id = 155, label = 'フォリッジグリーン'},
        },
        Metal = {
            {id = 117, label = 'ブラシドスチール'},
            {id = 118, label = 'ブラシドブラックスチール'},
            {id = 119, label = 'ブラシドアルミニウム'},
            {id = 120, label = 'クローム'},
            {id = 158, label = 'ピュアゴールド'},
            {id = 159, label = 'ブラシドゴールド'},
        },
        Worn = {
            {id = 21,  label = 'ブラック'},
            {id = 22,  label = 'グラファイト'},
            {id = 23,  label = 'シルバーグレー'},
            {id = 24,  label = 'シルバー'},
            {id = 25,  label = 'ブルーシルバー'},
            {id = 26,  label = 'シャドウシルバー'},
            {id = 46,  label = 'レッド'},
            {id = 47,  label = 'ゴールデンレッド'},
            {id = 48,  label = 'ダークレッド'},
            {id = 58,  label = 'ダークグリーン'},
            {id = 59,  label = 'グリーン'},
            {id = 60,  label = 'シーウォッシュ'},
            {id = 85,  label = 'ダークブルー'},
            {id = 86,  label = 'ブルー'},
            {id = 87,  label = 'ライトブルー'},
            {id = 113, label = 'ハニーベージュ'},
            {id = 114, label = 'ブラウン'},
            {id = 115, label = 'ダークブラウン'},
            {id = 116, label = 'ストローベージュ'},
            {id = 121, label = 'オフホワイト'},
            {id = 123, label = 'オレンジ'},
            {id = 124, label = 'ライトオレンジ'},
            {id = 126, label = 'タクシーイエロー'},
            {id = 130, label = 'オレンジ'},
            {id = 132, label = 'ホワイト'},
            {id = 133, label = 'オリーブアーミーグリーン'},
        },
        Chameleon = {
            {id = 161, label = 'アノダイズド・レッドパール'},
            {id = 162, label = 'アノダイズド・ワインパール'},
            {id = 163, label = 'アノダイズド・パープルパール'},
            {id = 164, label = 'アノダイズド・ブルーパール'},
            {id = 165, label = 'アノダイズド・グリーンパール'},
            {id = 166, label = 'アノダイズド・ライムパール'},
            {id = 167, label = 'アノダイズド・コッパーパール'},
            {id = 168, label = 'アノダイズド・ブロンズパール'},
            {id = 169, label = 'アノダイズド・シャンパニュパール'},
            {id = 170, label = 'アノダイズド・ゴールドパール'},
            {id = 171, label = 'グリーン/ブルー フリップ'},
            {id = 172, label = 'グリーン/レッド フリップ'},
            {id = 173, label = 'グリーン/ブラウン フリップ'},
            {id = 174, label = 'グリーン/ターコイズ フリップ'},
            {id = 175, label = 'グリーン/パープル フリップ'},
            {id = 176, label = 'ティール/パープル フリップ'},
            {id = 177, label = 'ターコイズ/レッド フリップ'},
            {id = 178, label = 'ターコイズ/パープル フリップ'},
            {id = 179, label = 'シアン/パープル フリップ'},
            {id = 180, label = 'ブルー/ピンク フリップ'},
            {id = 181, label = 'ブルー/グリーン フリップ'},
            {id = 182, label = 'パープル/レッド フリップ'},
            {id = 183, label = 'パープル/グリーン フリップ'},
            {id = 184, label = 'マゼンタ/グリーン フリップ'},
            {id = 185, label = 'マゼンタ/イエロー フリップ'},
            {id = 186, label = 'バーガンディ/グリーン フリップ'},
            {id = 187, label = 'マゼンタ/シアン フリップ'},
            {id = 188, label = 'コッパー/パープル フリップ'},
            {id = 189, label = 'マゼンタ/オレンジ フリップ'},
            {id = 190, label = 'レッド/オレンジ フリップ'},
            {id = 191, label = 'オレンジ/パープル フリップ'},
            {id = 192, label = 'オレンジ/ブルー フリップ'},
            {id = 193, label = 'ホワイト/パープル フリップ'},
            {id = 194, label = 'レッド/レインボー フリップ'},
            {id = 195, label = 'ブルー/レインボー フリップ'},
            {id = 196, label = 'ダークグリーンパール'},
            {id = 197, label = 'ダークティールパール'},
            {id = 198, label = 'ダークブルーパール'},
            {id = 199, label = 'ダークパープルパール'},
            {id = 200, label = 'オイルスリックパール'},
            {id = 201, label = 'ライトグリーンパール'},
            {id = 202, label = 'ライトブルーパール'},
            {id = 203, label = 'ライトパープルパール'},
            {id = 204, label = 'ライトピンクパール'},
            {id = 205, label = 'オフホワイトパール'},
            {id = 206, label = 'キュートピンクパール'},
            {id = 207, label = 'ベビーイエローパール'},
            {id = 208, label = 'ベビーグリーンパール'},
            {id = 209, label = 'ベビーブルーパール'},
            {id = 210, label = 'クリームパール'},
            {id = 211, label = 'ホワイト・プリズマティックパール'},
            {id = 212, label = 'グラファイト・プリズマティックパール'},
            {id = 213, label = 'ブルー・プリズマティックパール'},
            {id = 214, label = 'パープル・プリズマティックパール'},
            {id = 215, label = 'ホットピンク・プリズマティックパール'},
            {id = 216, label = 'レッド・プリズマティックパール'},
            {id = 217, label = 'グリーン・プリズマティックパール'},
            {id = 218, label = 'ブラック・プリズマティックパール'},
            {id = 219, label = 'オイルスピル・プリズマティックパール'},
            {id = 220, label = 'レインボー・プリズマティックパール'},
            {id = 221, label = 'ブラック・ホログラフィックパール'},
            {id = 222, label = 'ホワイト・ホログラフィックパール'},
            {id = 223, label = '吹雪城スペシャル: モノクローム'},
            {id = 224, label = '吹雪城スペシャル: ナイト＆デイ'},
            {id = 225, label = '吹雪城スペシャル: ザ・フェアリーラー'},
            {id = 226, label = '吹雪城スペシャル: スプランク・エクストリーム'},
            {id = 227, label = '吹雪城スペシャル: バイスシティ'},
            {id = 228, label = '吹雪城スペシャル: シンセウェーブ・ナイト'},
            {id = 229, label = '吹雪城スペシャル: 四季'},
            {id = 230, label = '吹雪城スペシャル: M9 スローバック'},
            {id = 231, label = '吹雪城スペシャル: バブルガム'},
            {id = 232, label = '吹雪城スペシャル: フルレインボー'},
            {id = 233, label = '吹雪城スペシャル: サンセット'},
            {id = 234, label = '吹雪城スペシャル: ザ・セブン'},
            {id = 235, label = '吹雪城スペシャル: 仮面ライダー'},
            {id = 236, label = '吹雪城スペシャル: クロマティック'},
            {id = 237, label = '吹雪城スペシャル: メリークリスマス!'},
            {id = 238, label = '吹雪城スペシャル: テンパラチャー'},
            {id = 239, label = '吹雪城スペシャル: HSW バッジ'},
            {id = 240, label = '吹雪城スペシャル: アノダイズド・ライトニング'},
            {id = 241, label = '吹雪城スペシャル: エメラルド'},
            {id = 242, label = '吹雪城スペシャル: 吹雪城'},
        }
    },
    modLabels = {
        [11] = { -- Engine
            {id = -1, label = 'ノーマル'},
            {id = 0,  label = 'エンジン 1'},
            {id = 1,  label = 'エンジン 2'},
            {id = 2,  label = 'エンジン 3'},
            {id = 3,  label = 'エンジン 4'},
        },
        [12] = { -- Brake
            {id = -1, label = 'ノーマル'},
            {id = 0,  label = 'ブレーキ 1'},
            {id = 1,  label = 'ブレーキ 2'},
            {id = 2,  label = 'ブレーキ 3'},
        },
        [13] = { -- Transmission
            {id = -1, label = 'ノーマル'},
            {id = 0,  label = 'トランスミッション 1'},
            {id = 1,  label = 'トランスミッション 2'},
            {id = 2,  label = 'トランスミッション 3'},
            {id = 3,  label = 'トランスミッション 4'},
        },
        [14] = { -- Horn
            {id = 0,  label = 'トラックホーン'},
            {id = 1,  label = 'ポリスホーン'},
            {id = 2,  label = 'ピエロホーン'},
            {id = 3,  label = 'ミュージカルホーン 1'},
            {id = 4,  label = 'ミュージカルホーン 2'},
            {id = 5,  label = 'ミュージカルホーン 3'},
            {id = 6,  label = 'ミュージカルホーン 4'},
            {id = 7,  label = 'ミュージカルホーン 5'},
            {id = 8,  label = '悲しいトロンボーン'},
            {id = 9,  label = 'クラシックホーン 1'},
            {id = 10, label = 'クラシックホーン 2'},
            {id = 11, label = 'クラシックホーン 3'},
            {id = 12, label = 'クラシックホーン 4'},
            {id = 13, label = 'クラシックホーン 5'},
            {id = 14, label = 'クラシックホーン 6'},
            {id = 15, label = 'クラシックホーン 7'},
            {id = 16, label = '音階 - ド'},
            {id = 17, label = '音階 - レ'},
            {id = 18, label = '音階 - ミ'},
            {id = 19, label = '音階 - ファ'},
            {id = 20, label = '音階 - ソ'},
            {id = 21, label = '音階 - ラ'},
            {id = 22, label = '音階 - シ'},
            {id = 23, label = '音階 - ド'},
            {id = 24, label = 'ジャズホーン 1'},
            {id = 25, label = 'ジャズホーン 2'},
            {id = 26, label = 'ジャズホーン 3'},
            {id = 27, label = 'ジャズホーン ループ'},
            {id = 28, label = '星条旗 1'},
            {id = 29, label = '星条旗 2'},
            {id = 30, label = '星条旗 3'},
            {id = 31, label = '星条旗 4'},
            {id = 32, label = 'クラシックホーン 8 ループ'},
            {id = 33, label = 'クラシックホーン 9 ループ'},
            {id = 34, label = 'クラシックホーン 10 ループ'},
            {id = 35, label = 'クラシックホーン 8'},
            {id = 36, label = 'クラシックホーン 9'},
            {id = 37, label = 'クラシックホーン 10'},
            {id = 38, label = '葬奏曲 ループ'},
            {id = 39, label = '葬奏曲'},
            {id = 40, label = 'お化け屋敷 ループ'},
            {id = 41, label = 'お化け屋敷'},
            {id = 42, label = 'サンアンドレアス ループ'},
            {id = 43, label = 'サンアンドレアス'},
            {id = 44, label = 'リバティーシティ ループ'},
            {id = 45, label = 'リバティーシティ'},
            {id = 46, label = 'お祭 1 ループ'},
            {id = 47, label = 'お祭 1'},
            {id = 48, label = 'お祭 2 ループ'},
            {id = 49, label = 'お祭 2'},
            {id = 50, label = 'お祭 3 ループ'},
            {id = 51, label = 'お祭 3'},
            {id = 52, label = 'エアホーン 低 ループ'},
            {id = 53, label = 'エアホーン 低'},
            {id = 54, label = 'エアホーン 中 ループ'},
            {id = 55, label = 'エアホーン 中'},
            {id = 56, label = 'エアホーン 高 ループ'},
            {id = 57, label = 'エアホーン 高'},
        },
        [15] = { -- Suspension
            {id = -1, label = 'ノーマル'},
            {id = 0,  label = 'サスペンション 1'},
            {id = 1,  label = 'サスペンション 2'},
            {id = 2,  label = 'サスペンション 3'},
            {id = 3,  label = 'サスペンション 4'},
            {id = 4,  label = 'サスペンション 5'},
        },
        [16] = { -- Armor
            {id = -1, label = 'なし'},
            {id = 0,  label = 'アーマー 1'},
            {id = 1,  label = 'アーマー 2'},
            {id = 2,  label = 'アーマー 3'},
            {id = 3,  label = 'アーマー 4'},
            {id = 4,  label = 'アーマー 5'},
        },
    },
    xenon = {
        {id = -1, label = 'デフォルト'},
        {id = 0,  label = 'ホワイト'},
        {id = 1,  label = 'ブルー'},
        {id = 2,  label = 'エレクトリックブルー'},
        {id = 3,  label = 'ミントグリーン'},
        {id = 4,  label = 'ライムグリーン'},
        {id = 5,  label = 'イエロー'},
        {id = 6,  label = 'ゴールデンシャワー'},
        {id = 7,  label = 'オレンジ'},
        {id = 8,  label = 'レッド'},
        {id = 9,  label = 'ポニーピンク'},
        {id = 10, label = 'ホットピンク'},
        {id = 11, label = 'パープル'},
        {id = 12, label = 'ブラックライト'},
    },
    windowTints = {
        {id = 0, label = 'なし'},
        {id = 1, label = 'ピュアブラック'},
        {id = 2, label = 'ダークスモーク'},
        {id = 3, label = 'ライトスモーク'},
        {id = 4, label = 'ノーマル'},
        {id = 5, label = 'グリーン'},
    },
    plateIndexes = {
        {id = 0, label = 'ホワイト/ブルー 1'},
        {id = 1, label = 'ブラック/イエロー'},
        {id = 2, label = 'ブルー/イエロー'},
        {id = 3, label = 'ホワイト/ブルー 2'},
        {id = 4, label = 'ホワイト/ブルー 3'},
        {id = 5, label = 'ヤンクトン'},
        {id = 6, label = 'エコーラ'},
        {id = 7, label = 'ラスベンチュラス'},
        {id = 8, label = 'リバティーシティ'},
        {id = 9, label = 'LSカーミート'},
        {id = 10, label = 'LSパニック'},
        {id = 11, label = 'パウンダーズ・オールスターズ'},
        {id = 12, label = 'スプランク'}
    },
    neon = {
        {id = 0, label = '左'},
        {id = 1, label = '右'},
        {id = 2, label = '前方'},
        {id = 3, label = '後方'},
    },
    neonColors = {
        {label = 'ホワイト',         r = 222, g = 222, b = 255},
        {label = 'ブルー',          r = 2,   g = 21,  b = 255},
        {label = 'エレクトリックブルー', r = 3,   g = 83,  b = 255},
        {label = 'ミントグリーン',    r = 0,   g = 255, b = 140},
        {label = 'ライムグリーン',    r = 94,  g = 255, b = 1},
        {label = 'イエロー',        r = 255, g = 255, b = 0},
        {label = 'ゴールデンシャワー', r = 255, g = 150, b = 0},
        {label = 'オレンジ',        r = 255, g = 62,  b = 0},
        {label = 'レッド',           r = 255, g = 1,   b = 1},
        {label = 'ポニーピンク',     r = 255, g = 50,  b = 100},
        {label = 'ホットピンク',      r = 255, g = 5,   b = 190},
        {label = 'パープル',        r = 35,  g = 1,   b = 255},
        {label = 'ブラックライト',    r = 15,  g = 3,   b = 255},
    },
    tyreSmoke = {
        {label = 'ホワイトスモーク',  r = 254, g = 254, b = 254},
        {label = 'ブラックスモーク',  r = 1,   g = 1,   b = 1},
        {label = 'ブルースモーク',   r = 0,   g = 150, b = 255},
        {label = 'イエロースモーク', r = 255, g = 255, b = 50},
        {label = 'オレンジスモーク', r = 255, g = 153, b = 51},
        {label = 'レッドスモーク',    r = 255, g = 10,  b = 10},
        {label = 'グリーンスモーク',  r = 10,  g = 255, b = 10},
        {label = 'パープルスモーク', r = 153, g = 10,  b = 153},
        {label = 'ピンクスモーク',   r = 255, g = 102, b = 178},
        {label = 'グレースモーク',   r = 128, g = 128, b = 128},
    },
    wheels = {
        {id = 0, label = 'スポーツ'},
        {id = 1, label = 'マッスル'},
        {id = 2, label = 'ローライダー'},
        {id = 3, label = 'SUV'},
        {id = 4, label = 'オフロード'},
        {id = 5, label = 'チューナー'},
        {id = 6, label = 'バイク(前輪)'},
        {id = 7, label = 'ハイエンド'},
        {id = 8, label = 'ベニーズ・オリジナル'},
        {id = 9, label = 'ベニーズ・カスタム'},
        {id = 10, label = 'オープンホイール'},
        {id = 11, label = 'ストリート'},
        {id = 12, label = 'トラック'},
    }
}
